/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'onlineVetConsultation' : IDL.Null,
  'clinicGrooming' : IDL.Null,
  'atHomeTreatment' : IDL.Null,
  'atHomeGrooming' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PetType = IDL.Variant({
  'cat' : IDL.Null,
  'dog' : IDL.Null,
  'other' : IDL.Null,
});
export const Time = IDL.Int;
export const Appointment = IDL.Record({
  'service' : ServiceType,
  'status' : AppointmentStatus,
  'ownerName' : IDL.Text,
  'email' : IDL.Text,
  'preferredTimeSlot' : IDL.Text,
  'petName' : IDL.Text,
  'petType' : PetType,
  'preferredDate' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAppointmentsByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'submitAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
  'submitContactMessage' : IDL.Func([ContactMessage], [IDL.Nat], []),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'onlineVetConsultation' : IDL.Null,
    'clinicGrooming' : IDL.Null,
    'atHomeTreatment' : IDL.Null,
    'atHomeGrooming' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PetType = IDL.Variant({
    'cat' : IDL.Null,
    'dog' : IDL.Null,
    'other' : IDL.Null,
  });
  const Time = IDL.Int;
  const Appointment = IDL.Record({
    'service' : ServiceType,
    'status' : AppointmentStatus,
    'ownerName' : IDL.Text,
    'email' : IDL.Text,
    'preferredTimeSlot' : IDL.Text,
    'petName' : IDL.Text,
    'petType' : PetType,
    'preferredDate' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAppointmentsByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'submitAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
    'submitContactMessage' : IDL.Func([ContactMessage], [IDL.Nat], []),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };