/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'service' : ServiceType,
  'status' : AppointmentStatus,
  'ownerName' : string,
  'email' : string,
  'preferredTimeSlot' : string,
  'petName' : string,
  'petType' : PetType,
  'preferredDate' : string,
  'notes' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type PetType = { 'cat' : null } |
  { 'dog' : null } |
  { 'other' : null };
export type ServiceType = { 'onlineVetConsultation' : null } |
  { 'clinicGrooming' : null } |
  { 'atHomeTreatment' : null } |
  { 'atHomeGrooming' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAppointmentsByEmail' : ActorMethod<[string], Array<Appointment>>,
  'submitAppointment' : ActorMethod<[Appointment], bigint>,
  'submitContactMessage' : ActorMethod<[ContactMessage], bigint>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];