/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactMessage {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export type Time = bigint;
export interface Appointment {
    service: ServiceType;
    status: AppointmentStatus;
    ownerName: string;
    email: string;
    preferredTimeSlot: string;
    petName: string;
    petType: PetType;
    preferredDate: string;
    notes: string;
    timestamp: Time;
    phone: string;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum PetType {
    cat = "cat",
    dog = "dog",
    other = "other"
}
export enum ServiceType {
    onlineVetConsultation = "onlineVetConsultation",
    clinicGrooming = "clinicGrooming",
    atHomeTreatment = "atHomeTreatment",
    atHomeGrooming = "atHomeGrooming"
}
export interface backendInterface {
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllContactMessages(): Promise<Array<ContactMessage>>;
    getAppointmentsByEmail(email: string): Promise<Array<Appointment>>;
    submitAppointment(appointment: Appointment): Promise<bigint>;
    submitContactMessage(contactMessage: ContactMessage): Promise<bigint>;
    updateAppointmentStatus(appointmentId: bigint, newStatus: AppointmentStatus): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, PetType as _PetType, ServiceType as _ServiceType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactMessages();
            return result;
        }
    }
    async getAppointmentsByEmail(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByEmail(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByEmail(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAppointment(arg0: Appointment): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAppointment(to_candid_Appointment_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAppointment(to_candid_Appointment_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitContactMessage(arg0: ContactMessage): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0);
            return result;
        }
    }
    async updateAppointmentStatus(arg0: bigint, arg1: AppointmentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PetType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PetType): PetType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: _ServiceType;
    status: _AppointmentStatus;
    ownerName: string;
    email: string;
    preferredTimeSlot: string;
    petName: string;
    petType: _PetType;
    preferredDate: string;
    notes: string;
    timestamp: _Time;
    phone: string;
}): {
    service: ServiceType;
    status: AppointmentStatus;
    ownerName: string;
    email: string;
    preferredTimeSlot: string;
    petName: string;
    petType: PetType;
    preferredDate: string;
    notes: string;
    timestamp: Time;
    phone: string;
} {
    return {
        service: from_candid_ServiceType_n4(_uploadFile, _downloadFile, value.service),
        status: from_candid_AppointmentStatus_n6(_uploadFile, _downloadFile, value.status),
        ownerName: value.ownerName,
        email: value.email,
        preferredTimeSlot: value.preferredTimeSlot,
        petName: value.petName,
        petType: from_candid_PetType_n8(_uploadFile, _downloadFile, value.petType),
        preferredDate: value.preferredDate,
        notes: value.notes,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onlineVetConsultation: null;
} | {
    clinicGrooming: null;
} | {
    atHomeTreatment: null;
} | {
    atHomeGrooming: null;
}): ServiceType {
    return "onlineVetConsultation" in value ? ServiceType.onlineVetConsultation : "clinicGrooming" in value ? ServiceType.clinicGrooming : "atHomeTreatment" in value ? ServiceType.atHomeTreatment : "atHomeGrooming" in value ? ServiceType.atHomeGrooming : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cat: null;
} | {
    dog: null;
} | {
    other: null;
}): PetType {
    return "cat" in value ? PetType.cat : "dog" in value ? PetType.dog : "other" in value ? PetType.other : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n2(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Appointment_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Appointment): _Appointment {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PetType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PetType): _PetType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: ServiceType;
    status: AppointmentStatus;
    ownerName: string;
    email: string;
    preferredTimeSlot: string;
    petName: string;
    petType: PetType;
    preferredDate: string;
    notes: string;
    timestamp: Time;
    phone: string;
}): {
    service: _ServiceType;
    status: _AppointmentStatus;
    ownerName: string;
    email: string;
    preferredTimeSlot: string;
    petName: string;
    petType: _PetType;
    preferredDate: string;
    notes: string;
    timestamp: _Time;
    phone: string;
} {
    return {
        service: to_candid_ServiceType_n12(_uploadFile, _downloadFile, value.service),
        status: to_candid_AppointmentStatus_n14(_uploadFile, _downloadFile, value.status),
        ownerName: value.ownerName,
        email: value.email,
        preferredTimeSlot: value.preferredTimeSlot,
        petName: value.petName,
        petType: to_candid_PetType_n16(_uploadFile, _downloadFile, value.petType),
        preferredDate: value.preferredDate,
        notes: value.notes,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    onlineVetConsultation: null;
} | {
    clinicGrooming: null;
} | {
    atHomeTreatment: null;
} | {
    atHomeGrooming: null;
} {
    return value == ServiceType.onlineVetConsultation ? {
        onlineVetConsultation: null
    } : value == ServiceType.clinicGrooming ? {
        clinicGrooming: null
    } : value == ServiceType.atHomeTreatment ? {
        atHomeTreatment: null
    } : value == ServiceType.atHomeGrooming ? {
        atHomeGrooming: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PetType): {
    cat: null;
} | {
    dog: null;
} | {
    other: null;
} {
    return value == PetType.cat ? {
        cat: null
    } : value == PetType.dog ? {
        dog: null
    } : value == PetType.other ? {
        other: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
